forces encoding to UTF for a spec fix
  For some reason on JRuby this spec started causing a
  ArgumentError: Invalid byte sequence in UTF-8

  The failing spec is ensuring that when WebMock is off, it is possible to query to a real
  website, in this case google.

  The spec queries google, and then ensures the body of the response
  contains google.

  So all this fix does is force the response to be UTF, and get rid of
  any invalid characters. So now match can check for google in the provided string,
  without worrying about invalid characters it doesn't know how to handle.

  While knowing why we have to suddenly force encoding would be ideal,
  we know this change does not affect the integrity of the spec.