Fix error on redirection
When redirection is used there is the exception:
`HttpClientError: undefined method `http_GET_without_webmock' for #<Curl::Easy http://www.example.com>`
Since all the alias have been removed, this call should also be removed.